# Generated by Django 4.0.4 on 2022-04-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_created_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_bookings_done',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total bookings made by user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Balance'),
        ),
    ]
