# Generated by Django 4.0.4 on 2022-06-15 21:51

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone')),
                ('notes', models.TextField(blank=True, max_length=1024, verbose_name='Notes')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_until', models.DateField(verbose_name='Until')),
                ('time_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time period')),
                ('time_unit', models.CharField(blank=True, default='nights', max_length=64, null=True, verbose_name='Time unit')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('single_room_count', models.PositiveIntegerField(default=0, verbose_name='Single Rooms')),
                ('double_room_count', models.PositiveIntegerField(default=0, verbose_name='Double Rooms')),
                ('triple_room_count', models.PositiveIntegerField(default=0, verbose_name='Triple Rooms')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='Number of Adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Number of Children')),
                ('transport', models.BooleanField(default=False, verbose_name='Transport')),
                ('seats_booked', models.BooleanField(default=False)),
                ('transport_price_person', models.DecimalField(decimal_places=0, default=400, max_digits=36, verbose_name='Transport price per person')),
                ('extra_seats', models.PositiveIntegerField(default=0, verbose_name='Number of extra seats')),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='discount percentage')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='discount amount')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='paid amount')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/destination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('intro', ckeditor.fields.RichTextField(blank=True)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, upload_to='images/hotels')),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotels', to='reservation.destination')),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_until', models.DateField(verbose_name='Until')),
                ('rooms_total', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='rooms total')),
                ('rooms_booked', models.PositiveBigIntegerField(default=0, verbose_name='rooms_booked')),
                ('bus_total', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='bus_total')),
                ('meeting_location', models.CharField(blank=True, max_length=256, verbose_name='Trip starting location')),
                ('meeting_time', models.CharField(blank=True, max_length=256, verbose_name='Trip starting time')),
                ('transport_price_person', models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='Transport price per person')),
                ('single_room_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='single room cost')),
                ('double_room_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='double room cost')),
                ('triple_room_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='triple room cost')),
                ('single_room_price', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price / Person')),
                ('double_room_price', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price / Person')),
                ('triple_room_price', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price/ Person')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reservations', to='reservation.hotel', verbose_name='accommodation')),
                ('creation_user', models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='reservation.destination', verbose_name='destination')),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('single_room_count', models.PositiveIntegerField(default=0, verbose_name='Single Rooms')),
                ('double_room_count', models.PositiveIntegerField(default=0, verbose_name='Double Rooms')),
                ('triple_room_count', models.PositiveIntegerField(default=0, verbose_name='Triple Rooms')),
                ('single_room_persons', models.PositiveIntegerField(default=0, verbose_name='Persons in Single Rooms')),
                ('double_room_persons', models.PositiveIntegerField(default=0, verbose_name='Persons in Double Rooms')),
                ('triple_room_persons', models.PositiveIntegerField(default=0, verbose_name='Persons in Triple Rooms')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='Adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Children')),
                ('extra_seats', models.PositiveIntegerField(default=0, verbose_name='Extra Seats')),
                ('seats_booked', models.BooleanField(default=False)),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='discount percentage')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='discount amount')),
                ('discount_cause', models.TextField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='Paid amount')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone number')),
                ('phone2', models.CharField(blank=True, max_length=256, verbose_name='Additional Phone number')),
                ('notes', models.TextField(blank=True, max_length=1024, verbose_name='Notes')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED')], default='active', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_bookings', to='reservation.client')),
                ('creation_user', models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_trip_bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservation.trip', verbose_name='Trip')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='TripProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cost', models.PositiveIntegerField(verbose_name='cost')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_programs', to='reservation.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TripBookingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('unit_cost', models.PositiveIntegerField()),
                ('unit_name', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='reservation.tripbooking')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='reservation.tripprogram')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='label')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_until', models.DateField(verbose_name='To')),
                ('single_room_half', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price, Half board')),
                ('single_room_half_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room cost, Half board')),
                ('single_room_full', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price, Full board')),
                ('single_room_full_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room cost, Full board')),
                ('double_room_half', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price, Half board')),
                ('double_room_half_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room cost, Half board')),
                ('double_room_full', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price, Full board')),
                ('double_room_full_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room cost, Full board')),
                ('triple_room_half', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price, Half board')),
                ('triple_room_half_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room cost, Half board')),
                ('triple_room_full', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price, Full board')),
                ('triple_room_full_cost', models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room cost, Full board')),
                ('creation_user', models.ForeignKey(null=True, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_packages', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='packages', to='reservation.hotel', verbose_name='Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='Message')),
                ('details', models.TextField(blank=True, max_length=4000, verbose_name='Details')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.booking', verbose_name='Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservation.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='reservation.accommodationtype', verbose_name='Accommodation type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibookings', to='reservation.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_user',
            field=models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservation.hotelpackage'),
        ),
        migrations.CreateModel(
            name='AdditionalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('reason', models.CharField(max_length=150)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_amounts', to='reservation.tripbooking')),
                ('ibooking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_amounts', to='reservation.booking')),
            ],
        ),
    ]
