# Generated by Django 4.0.4 on 2022-04-14 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('intro', models.TextField()),
                ('level', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('available', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotels', to='reservation.destination')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('phone', models.CharField(db_index=True, max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('with_bus', models.BooleanField(default=False)),
                ('nights', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('rooms', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('children', models.IntegerField()),
                ('notes', models.TextField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservation.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('price_per_person_night', models.DecimalField(decimal_places=0, default=1000, max_digits=10)),
                ('period', models.DurationField(blank=True, null=True, verbose_name='period')),
                ('accommodation_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservation.accommodationtype')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='packages', to='reservation.hotel')),
            ],
        ),
    ]
