# Generated by Django 4.0.4 on 2022-04-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
                ('notes', models.TextField(blank=True, max_length=1024, verbose_name='Notes')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='From')),
                ('date_until', models.DateTimeField(blank=True, null=True, verbose_name='Until')),
                ('time_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time period')),
                ('time_unit', models.CharField(blank=True, default='nights', max_length=64, verbose_name='Time unit')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('booking_id', models.CharField(blank=True, max_length=100, verbose_name='Booking ID')),
                ('adults', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Adults')),
                ('children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Children')),
                ('transport', models.BooleanField(default=False)),
                ('extra_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of extra seats')),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of total seats')),
                ('booking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Booking price')),
                ('transport_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Transport price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Total price')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Total price')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservation.hotel')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='Message')),
                ('details', models.TextField(blank=True, max_length=4000, verbose_name='Details')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.booking', verbose_name='Booking')),
            ],
        ),
        migrations.RenameField(
            model_name='hotelpackage',
            old_name='price_per_person_night',
            new_name='price_per_person_night_double',
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='price_per_person_night_single',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=10),
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reservation.hotelpackage'),
        ),
    ]
