# Generated by Django 4.0.4 on 2022-04-19 04:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0007_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='intro',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='From')),
                ('date_until', models.DateTimeField(blank=True, null=True, verbose_name='Until')),
                ('bus_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Number of buses')),
                ('transport_price_person', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Transport price per person')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='Trip starting location')),
                ('single_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Single Room price')),
                ('Double_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Double Room price')),
                ('Triple_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Triple Room price')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reservations', to='reservation.hotel')),
                ('creation_user', models.ForeignKey(blank=True, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='reservation.destination')),
            ],
        ),
    ]
