# Generated by Django 4.0.4 on 2022-04-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_hotel_intro_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Double_room_price',
            new_name='double_room_price',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='Triple_room_price',
            new_name='triple_room_price',
        ),
    ]
