# Generated by Django 4.0.4 on 2022-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_rename_double_room_price_trip_double_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_until',
            field=models.DateField(blank=True, null=True, verbose_name='Until'),
        ),
    ]
