# Generated by Django 4.0.4 on 2022-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_trip_date_from_alter_trip_date_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='bus_count',
            new_name='bus_total',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='location',
            new_name='meeting_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='rooms_booked',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Number of buses'),
        ),
        migrations.AddField(
            model_name='trip',
            name='rooms_total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Number of buses'),
        ),
    ]
