# Generated by Django 4.0.4 on 2022-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_rename_bus_count_trip_bus_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelpackage',
            name='price_per_person_night_double',
        ),
        migrations.RemoveField(
            model_name='hotelpackage',
            name='price_per_person_night_single',
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='double_room_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Double Room price, Full board'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='double_room_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Double Room price, Half board'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='single_room_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Single Room price, Full board'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='single_room_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Single Room price, Half board'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='triple_room_full',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Triple Room price, Full board'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='triple_room_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Triple Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
