# Generated by Django 4.0.4 on 2022-04-25 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0012_remove_hotelpackage_price_per_person_night_double_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpackage',
            name='double_room_full',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Double Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='double_room_half',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Double Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='single_room_full',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Single Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='single_room_half',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Single Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='triple_room_full',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Triple Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='triple_room_half',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Triple Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus_total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='bus_total'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rooms_booked',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='rooms_booked'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rooms_total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='rooms total'),
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('adults', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Adults')),
                ('children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Children')),
                ('extra_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of extra seats')),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of total seats')),
                ('transport_price_person', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Transport price per person')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone number')),
                ('phone2', models.CharField(blank=True, max_length=256, verbose_name='Additional Phone number')),
                ('notes', models.TextField(blank=True, max_length=1024, verbose_name='Notes')),
                ('creation_user', models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_trip_bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservation.trip')),
            ],
        ),
    ]
