# Generated by Django 4.0.4 on 2022-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_hotelpackage_double_room_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='double_room_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of double rooms'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='single_room_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of single rooms'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='triple_room_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of triple rooms'),
        ),
    ]
