# Generated by Django 4.0.4 on 2022-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_tripbooking_double_room_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='adults',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Adults'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Children'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='double_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of double rooms'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='extra_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of extra seats'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='single_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of single rooms'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='triple_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of triple rooms'),
        ),
    ]
