# Generated by Django 4.0.4 on 2022-04-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_alter_tripbooking_adults_alter_tripbooking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
