# Generated by Django 4.0.4 on 2022-04-28 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_hotel_featured_alter_hotel_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripbooking',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='double_room_persons',
            field=models.PositiveIntegerField(default=0, verbose_name='Persons in Double Rooms'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='single_room_persons',
            field=models.PositiveIntegerField(default=0, verbose_name='Persons in Single Rooms'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='triple_room_persons',
            field=models.PositiveIntegerField(default=0, verbose_name='Persons in Triple Rooms'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='double_room_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Double Room price / Person'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='single_room_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Single Room price / Person'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_price_person',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Transport price per person'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='triple_room_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Triple Room price/ Person'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='adults',
            field=models.PositiveIntegerField(default=0, verbose_name='Adults'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='double_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Double Rooms'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='extra_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Extra Seats'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='single_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Single Rooms'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='triple_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Triple Rooms'),
        ),
    ]
