# Generated by Django 4.0.4 on 2022-04-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_remove_tripbooking_total_seats_tripbooking_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripbooking',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='Deduction'),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='discount_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='transport_price_person',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=36, null=True, verbose_name='Transport price per person'),
        ),
    ]
