# Generated by Django 4.0.4 on 2022-04-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_rename_discount_tripbooking_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='discount amount'),
        ),
        migrations.CreateModel(
            name='TripProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_programs', to='reservation.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TripBookingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='reservation.tripbooking')),
                ('program', models.ForeignKey(on_delete=models.SET('Deleted program'), related_name='bookings', to='reservation.tripprogram')),
            ],
        ),
    ]
