# Generated by Django 4.0.4 on 2022-04-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_tripbooking_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reservations', to='reservation.hotel', verbose_name='accommodation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='reservation.destination', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservation.trip', verbose_name='Trip'),
        ),
    ]
