# Generated by Django 4.0.4 on 2022-05-08 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0023_alter_trip_options_alter_tripbooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transport_price',
        ),
        migrations.RemoveField(
            model_name='hotelpackage',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='transport_price_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='reservation.accommodationtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_user',
            field=models.ForeignKey(default=1, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='discount percentage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='double_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Double Rooms'),
        ),
        migrations.AddField(
            model_name='booking',
            name='single_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Single Rooms'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_price_person',
            field=models.DecimalField(decimal_places=0, default=400, max_digits=36, verbose_name='Transport price per person'),
        ),
        migrations.AddField(
            model_name='booking',
            name='triple_room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Triple Rooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Adults'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Children'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_until',
            field=models.DateTimeField(verbose_name='Until'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of extra seats'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservation.hotelpackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='paid amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='creation_user',
            field=models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_until',
            field=models.DateField(verbose_name='Until'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rooms_booked',
            field=models.PositiveBigIntegerField(default=0, verbose_name='rooms_booked'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_price_person',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=36, verbose_name='Transport price per person'),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='discount percentage'),
        ),
    ]
