# Generated by Django 4.0.4 on 2022-05-09 08:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0024_remove_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpackage',
            name='creation_user',
            field=models.ForeignKey(default=1, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
