# Generated by Django 4.0.4 on 2022-05-09 10:38

from django.conf import settings
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0025_hotelpackage_creation_user_alter_hotel_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelpackage',
            old_name='date_to',
            new_name='date_until',
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='creation_user',
            field=models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
