# Generated by Django 4.0.4 on 2022-05-11 16:07

from django.conf import settings
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0026_rename_date_to_hotelpackage_date_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creation_user',
            field=models.ForeignKey(on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_unit',
            field=models.CharField(blank=True, default='nights', max_length=64, null=True, verbose_name='Time unit'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='creation_user',
            field=models.ForeignKey(blank=True, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='date_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='double_room_full',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='double_room_half',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='single_room_full',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='single_room_half',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price, Half board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='triple_room_full',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price, Full board'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='triple_room_half',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price, Half board'),
        ),
    ]
