# Generated by Django 4.0.4 on 2022-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_alter_booking_creation_user_alter_booking_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpackage',
            name='double_room_full_cost',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=36, verbose_name='Double Room cost, Full board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='double_room_half_cost',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=36, verbose_name='Double Room cost, Half board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='single_room_full_cost',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=36, verbose_name='Single Room cost, Full board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='single_room_half_cost',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=36, verbose_name='Single Room cost, Half board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='triple_room_full_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=36, verbose_name='Triple Room cost, Full board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='triple_room_half_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=36, verbose_name='Triple Room cost, Half board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='double_room_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=36, verbose_name='double room cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=256, verbose_name='Trip starting time'),
        ),
        migrations.AddField(
            model_name='trip',
            name='single_room_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=36, verbose_name='single room cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='triple_room_cost',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=36, verbose_name='triple room cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='double_room_price',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Double Room price / Person'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='single_room_price',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Single Room price / Person'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='triple_room_price',
            field=models.DecimalField(decimal_places=0, max_digits=36, verbose_name='Triple Room price/ Person'),
        ),
    ]
