# Generated by Django 4.0.4 on 2022-05-16 23:19

from django.conf import settings
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0028_hotelpackage_double_room_full_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_until',
            field=models.DateField(verbose_name='Until'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(reservation.models.get_sentinel_user), related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
