# Generated by Django 4.0.4 on 2022-05-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0029_alter_booking_date_from_alter_booking_date_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_until',
            field=models.DateTimeField(verbose_name='Until'),
        ),
    ]
