# Generated by Django 4.0.4 on 2022-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_alter_booking_date_from_alter_booking_date_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_until',
            field=models.DateField(verbose_name='Until'),
        ),
    ]
