# Generated by Django 4.0.4 on 2022-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0032_booking_status_tripbooking_status_tripprogram_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('reservations', models.PositiveBigIntegerField(default=1)),
                ('last_reservation', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED')], default='active', max_length=20),
        ),
    ]
