# Generated by Django 4.0.4 on 2022-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_client_alter_booking_status_alter_tripbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='seats_booked',
            field=models.BooleanField(default=False),
        ),
    ]
