# Generated by Django 4.0.4 on 2022-05-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0034_tripbooking_seats_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_amounts', to='reservation.tripbooking')),
            ],
        ),
    ]
