# Generated by Django 4.0.4 on 2022-05-31 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0035_additionalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalamount',
            name='reason',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
