# Generated by Django 4.0.4 on 2022-05-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0036_additionalamount_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_reservation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reservations',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibookings', to='reservation.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_bookings', to='reservation.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
