# Generated by Django 4.0.4 on 2022-06-15 21:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date_1', models.DateField()),
                ('date_2', models.DateField()),
                ('start_location', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_to', to='reservation.destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_from', to='reservation.destination')),
            ],
            options={
                'ordering': ['-date_1'],
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone number')),
                ('phone2', models.CharField(blank=True, max_length=256, verbose_name='Additional Phone number')),
                ('notes', models.TextField(blank=True, max_length=1024, verbose_name='Notes')),
                ('seats_count', models.PositiveIntegerField()),
                ('seats_booked', models.BooleanField(default=False)),
                ('Bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bus_only_bookings', to='transport.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(49)])),
                ('booking_type', models.CharField(choices=[('trip', 'TRIP'), ('individual', 'INDIVIDUAL'), ('other', 'OTHER')], max_length=15)),
                ('seat_type', models.CharField(choices=[('going', 'GOING'), ('return', 'RETURN'), ('both', 'BOTH')], max_length=15)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transport.bus')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_seats', to='reservation.tripbooking')),
                ('bus_only_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_seats', to='transport.busbooking')),
                ('ibooking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_seats', to='reservation.booking')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('Bus', 'number', 'seat_type'), name='unique seat'),
        ),
    ]
