# Generated by Django 4.0.4 on 2022-05-26 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0033_client_alter_booking_status_alter_tripbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('date_1', models.DateField()),
                ('date_2', models.DateField()),
                ('start_location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='reservation.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(49)])),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transport.bus')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_seats', to='reservation.tripbooking')),
            ],
        ),
    ]
