# Generated by Django 4.0.4 on 2022-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['-date_1']},
        ),
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
