# Generated by Django 4.0.4 on 2022-05-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_client_alter_booking_status_alter_tripbooking_status'),
        ('transport', '0002_alter_bus_options_alter_bus_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buses_from', to='reservation.destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_to', to='reservation.destination'),
        ),
    ]
