# Generated by Django 4.0.4 on 2022-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_bus_origin_alter_bus_destination'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('Bus', 'number'), name='unique seat'),
        ),
    ]
